// Generated by CoffeeScript 1.6.2
var app, asset, express, fs, http, master, path, server, _i, _len, _ref;

http = require('http');

fs = require('fs');

path = require('path');

master = require('./lib/master');

express = require('express');

app = express();

global.appConfig = require('./appConfig');

app.use(express.favicon());

_ref = ['/css', '/img', '/js', '/html'];
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  asset = _ref[_i];
  app.use(asset, express["static"](__dirname + '/assets' + asset));
}

app.get('/', function(req, res) {
  return res.end("server is ok");
});

app.get('/status', function(req, res) {
  var slave, slave1, slaves;

  res.writeHead(200, {
    'Content-Type': 'text/html;charset=utf-8'
  });
  slaves = master.getConnSlaves();
  slave1 = [];
  slaves = (function() {
    var _j, _len1, _results;

    _results = [];
    for (_j = 0, _len1 = slaves.length; _j < _len1; _j++) {
      slave = slaves[_j];
      _results.push(JSON.stringify(slave));
    }
    return _results;
  })();
  return res.end("当前服务器：<br />" + slaves.join('<br />'));
});

app.get('/api/:action/:id?', function(req, res) {
  var action;

  res.setHeader("Content-Type", 'text/javascript;charset=utf-8');
  action = require('./api/' + req.params.action.toLowerCase());
  return action.get(req, res);
});

app.use(function(err, req, res, next) {
  console.error(err.stack);
  if (req.accepts('json')) {
    return res.send({
      error: 'Not found'
    });
  }
  if (req.accepts('html')) {
    return res.render('404', {
      url: req.url
    });
  }
  return res.type('txt').send('Not found');
});

server = http.createServer(app);

require('./lib/master').listen(server);

server.listen(appConfig.port);

console.log("同步服务正在运行，请不要关闭...");

require('./lib/slave');
