// Generated by CoffeeScript 1.6.2
var config, configfile, defaultConfig, fs, key, path, val;

fs = require("fs");

path = require('path');

defaultConfig = {
  "debug": false,
  "logger": true,
  "masterHost": "http://42.121.119.196",
  "projectRoot": "d:\\web\\",
  "port": 8656,
  "runAs": "slave",
  "watchInterval": 5,
  "remoteGit": "http://administrator:yftech258456@42.121.119.196:8655/",
  "projects": {
    "filesyn": {
      "root": "d:\\web\\",
      "dir": "filesyn"
    }
  }
};

configfile = path.join(__dirname, 'config', 'config.json');

if (fs.existsSync(configfile)) {
  config = require('./config/config.json');
  for (key in config) {
    val = config[key];
    defaultConfig[key] = val;
  }
}

defaultConfig.config = defaultConfig.config || {};

defaultConfig.getProjectInfo = function(project) {
  var projectInfo, repo;

  project = project.toLowerCase();
  if (defaultConfig.projects[project]) {
    repo = defaultConfig.projects[project];
    projectInfo = {
      root: repo.root,
      dir: repo.dir || project
    };
  } else {
    projectInfo = {
      root: defaultConfig.projectRoot,
      dir: project
    };
  }
  projectInfo.exists = function() {
    return fs.existsSync(projectInfo.root + projectInfo.dir);
  };
  return projectInfo;
};

module.exports = defaultConfig;

global.appConfig = defaultConfig;
