// Generated by CoffeeScript 1.6.2
var mailOptions, nodemailer, smtpTransport;

nodemailer = require("nodemailer");

smtpTransport = nodemailer.createTransport("SMTP", {
  host: "smtp.yftech.com",
  auth: {
    user: "map_service@yftech.com",
    pass: "www.yfbar.com"
  }
});

mailOptions = {
  from: "map_service✔ <map_service@yftech.com>",
  to: "zhulin@yftech.com",
  subject: "同步失败文件 ✔",
  text: "服务器监听同步失败 ✔",
  html: "<b>Hello world ✔</b>"
};

exports.sendMail = function(opt) {
  opt.from = opt.from || mailOptions.from;
  opt.to = opt.from || mailOptions.to;
  opt.subject = opt.from || mailOptions.subject;
  opt.text = opt.from || mailOptions.text;
  opt.html = opt.from || mailOptions.html;
  return smtpTransport.sendMail(opt);
};

mailOptions = {
  from: "map_service✔ <map_service@yftech.com>",
  to: "bar@blurdybloop.com, baz@blurdybloop.com",
  subject: "Hello ✔",
  text: "Hello world ✔",
  html: "<b>Hello world ✔</b>"
};
