// Generated by CoffeeScript 1.6.2
var mailOptions, nodemailer, smtpTransport;

nodemailer = require("nodemailer");

smtpTransport = nodemailer.createTransport("SMTP", {
  service: "smtpcom.263xmail.com",
  auth: {
    user: "map_service@yftech.com",
    pass: "www.yfbar.com"
  }
});

exports.sendMail = smtpTransport.sendMail;

mailOptions = {
  from: "map_service✔ <map_service@yftech.com>",
  to: "bar@blurdybloop.com, baz@blurdybloop.com",
  subject: "Hello ✔",
  text: "Hello world ✔",
  html: "<b>Hello world ✔</b>"
};
