// Generated by CoffeeScript 1.6.2
var dateformat, fs, helper, path, spawn;

path = require('path');

fs = require('fs');

dateformat = require('dateformat');

spawn = require('child_process').spawn;

helper = require('./helper');

module.exports = function(project, fn) {
  var cmd, emit, projectInfo;

  emit = function(event, msg) {
    fn({
      event: event,
      project: project,
      result: msg
    });
    return console.log(project + msg);
  };
  projectInfo = appConfig.getProjectInfo(project);
  if (!projectInfo.exists()) {
    return emit("notExist", "项目不存在");
  }
  emit("syncing", project);
  cmd = helper.exec('pull', project);
  return cmd.on("close", function(code) {
    var now, retrycmd;

    if (code !== 0) {
      retrycmd = helper.exec('pull', project);
      retrycmd.on("close", function(retryCode) {
        var now;

        if (code !== 0) {
          return emit("syncedError", cmd.error);
        }
        now = new Date();
        return emit("synced", dateformat(now, 'yyyy-mm-dd HH:MM:ss'));
      });
    }
    now = new Date();
    return emit("synced", dateformat(now, 'yyyy-mm-dd HH:MM:ss'));
  });
};
