// Generated by CoffeeScript 1.6.2
var dateformat, fs, helper, path, spawn;

path = require('path');

fs = require('fs');

dateformat = require('dateformat');

spawn = require('child_process').spawn;

helper = require('./helper');

module.exports = function(project, fn) {
  var cmd, emit, projectInfo;

  emit = function(event, msg) {
    return fn({
      event: event,
      project: project,
      result: msg
    });
  };
  projectInfo = appConfig.getProjectInfo(project);
  if (!projectInfo.exists()) {
    return emit("notExist", "项目不存在");
  }
  emit("syncing", "开始同步 " + project);
  cmd = helper.exec('pull', project);
  return cmd.on("close", function(code) {
    var now;

    if (code !== 0) {
      return emit("synced", "同步失败！！！\n" + cmd.error);
    }
    now = new Date();
    return emit("synced", "同步成功  " + dateformat(now, 'yyyy-mm-dd HH:MM:ss'));
  });
};
