// Generated by CoffeeScript 1.6.2
var dateformat, fs, helper, path, runCmd, spawn;

path = require('path');

fs = require('fs');

dateformat = require('dateformat');

spawn = require('child_process').spawn;

helper = require('./helper');

module.exports = function(project, client, send) {
  var emit, projectInfo;

  emit = function(event, msg) {
    console.log(msg);
    if (client != null) {
      client.emit(event, {
        project: project,
        result: msg
      });
    }
    if (send != null) {
      return send(event, {
        project: project,
        result: msg
      });
    }
  };
  projectInfo = appConfig.getProjectInfo(project);
  if (!projectInfo.exists()) {
    return emit("notExist", "项目不存在");
  }
  emit("syncing", "开始同步 " + project);
  return setTimeout((function() {
    return runCmd(project, emit);
  }), 200);
};

runCmd = function(project, emit) {
  var cmd;

  cmd = helper.exec('pull', project);
  return cmd.on("close", function(code) {
    var now;

    if (code !== 0) {
      return emit("synced", "同步失败！！！\n" + cmd.error);
    }
    now = new Date();
    return emit("synced", "同步成功  " + dateformat(now, 'yyyy-mm-dd HH:MM:ss'));
  });
};
