// Generated by CoffeeScript 1.6.2
var sync;

sync = require('../lib/sync');

exports.get = function(req, res, autoend) {
  var project, send;

  if (autoend == null) {
    autoend = true;
  }
  project = req.params.id;
  send = function(evt, msg) {
    var result;

    switch (evt) {
      case "syncing":
        return res.write('正在同步本地\n');
      default:
        if (msg) {
          result = msg.result || msg;
          if (autoend) {
            return res.end(result);
          } else {
            return res.write(result);
          }
        }
    }
  };
  return sync(project, null, send);
};
